### PR TITLE
PROD-601

### PR DESCRIPTION
**Pull request by jeffvarnam**
Passing Circle CI build: https://circleci.com/gh/loanlifecycle/design-system/26
- Added circle.yml for design-system

Reviewed by @dalefrancum-ncino

### CODE REVIEW

**Comment by dalefrancum** [comment]
@jeffvarnam , if you add this section (between dependencies and test), it will keep the Database processing from kicking off.

```
# Just stubbing this since there is no need for anything to run here.
database:
  pre:
    - echo "Database:pre section is empty."
  override:
    - echo "Database:override section is empty."
```

**Comment by dalefrancum** [comment]
You are cloning the master branch of force-framework.  Would you _always_ want that, or are there times where you'd want develop?  Just asking.

**Review by dalefrancum — APPROVED** [review]
@jeffvarnam - I left a couple of comments in the Conversation section, see what you think.

**Comment by jeffvarnam** [comment]
@dalefrancum-ncino Updated the database section and it already uses the develop branch when cloning force-framework

**Comment by dalefrancum** [comment]
@jeffvarnam - aye, I was looking at the deploy_toolkit checkout.

**Pull request merged**
