### PR TITLE
PROD-809

### PR DESCRIPTION
**Pull request by mikebernard**
- Added nDS styles for ChosenJS select component.

Reviewed by @BillyErwin 

JIRA Ticket: https://ncinodev.atlassian.net/browse/PROD-809
Build: https://ncinodev.atlassian.net/builds/browse/MANAGEDAPPS-DSCI16-5

---

This change is [Reviewable](https://reviewable.io/reviews/loanlifecycle/design-system/20)

### CODE REVIEW

**Comment by BillyErwin** [comment]
:lgtm: Nice work!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-:-KM-p0ODOD-31HaBEvxx:764048764)_

**Comment by BillyErwin** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/loanlifecycle/design-system/20)_

**Comment by matt-lukens** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 3 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-vYF_YXAnBmfIBYvr:-KM-vYF_YXAnBmfIBYvs:1240958473) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L3)):_

> ``` SCSS
> $nds-font-color: #16325C;
> $nds-border-color: #D8DDE6;
> $nds-border-radius: 4px;
> ```

Please use existing tokens for these values, https://www.lightningdesignsystem.com/tokens/.

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 16 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-vqBLcr--aDDwRqUm:-KM-vqBLcr--aDDwRqUn:-2006601692) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L16)):_

> ``` SCSS
>   border-color: $nds-border-color !important;
>   background-image: none !important;
> }
> ```

I believe there are existing mixins for border and shadow you can reuse.  Check the files in dependencies/ for the existing mixins.

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 28 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-wwQicY3qt0-mYNzx:-KM-wwQicY3qt0-mYNzy:-353346541) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L28)):_

> ``` SCSS
>       font-family: Salesforce Sans;
>       font-size: 14px;
>       height: 33px;
> ```

Please use tokens for values, most already exist.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/loanlifecycle/design-system/20)_

**Comment by mikebernard** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 3 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-vYF_YXAnBmfIBYvr:-KM0-Kv5Iyrj3wOQ-z-9:-499146009) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L3)):_
<details><summary>

<i>Previously, matt-lukens (Matt Lukens) wrote…</i></summary>



> Please use existing tokens for these values, https://www.lightningdesignsystem.com/tokens/.
> </details>
> Done.

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 16 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-vqBLcr--aDDwRqUm:-KM0OhsioEKm_dvnQK1n:-1476409552) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L16)):_
<details><summary>

<i>Previously, matt-lukens (Matt Lukens) wrote…</i></summary>



> I believe there are existing mixins for border and shadow you can reuse.  Check the files in dependencies/ for the existing mixins.
> </details>
> There were not mixins defined that will accommodate this. 

---

_[ui/components/forms/flavors/nds-chosen/index.scss, line 28 [r1]](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-KM-wwQicY3qt0-mYNzx:-KM0OtK8m7dp8bbgozsq:1897206134) ([raw file](https://github.com/loanlifecycle/design-system/blob/43d86fa961b05ede4d5c089716781a1e6f5bf6db/ui/components/forms/flavors/nds-chosen/index.scss#L28)):_
<details><summary>

<i>Previously, matt-lukens (Matt Lukens) wrote…</i></summary>



> Please use tokens for values, most already exist.
> </details>
> Was not aware of these! Thanks for pointing this out. I thought it looked clean before. Now it looks great!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/loanlifecycle/design-system/20)_

**Comment by matt-lukens** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/loanlifecycle/design-system/20#-:-KM1-AAR9_1oCRDh7nZl:1417088721)_

**Pull request merged**
